services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=notification_manager
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017
      - MongoDB__DatabaseName=notification_manager
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - mongodb
      - rabbitmq

  email-worker:
    build:
      context: .
      dockerfile: Dockerfile.email
    environment:
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017
      - MongoDB__DatabaseName=notification_manager
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - mongodb
      - rabbitmq

  push-worker:
    build:
      context: .
      dockerfile: Dockerfile.push
    environment:
      - ConnectionStrings__MongoDB=mongodb://mongodb:27017
      - MongoDB__DatabaseName=notification_manager
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  mongodb_data:
  rabbitmq_data: